
name: macOS

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
jobs:
  compile:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: bash mac-build.sh
      run: bash mac-build.sh
    - name: list
      run: ls && ls oni2 && ls oni2/_release
    - name: zip app
      run: zip -r onivim.zip oni2/_release/Onivim2.app/
    - name: 'Upload Artifact '
      uses: actions/upload-artifact@v2
      with:
          name: onivim.zip
          path: ./onivim.zip
